### ISSUE TITLE
[rbac-manager] Unable to install with Helm 3

### ISSUE THREAD

**Issue by bittermandel** [FairwindsOps/charts#276]
**Describe the bug**
When installing `fairwinds-stable/rbac-manager` using helm3, validation fails with the following error:
`Error: validation: chart.metadata is required`

**To Reproduce**
1. `helm install fairwinds-stable/rbac-manager rbac-manager --namespace rbac-manager`

**Expected behavior**
Should install the chart as intended.

**CLI Output**
Error: validation: chart.metadata is required

**Environment (please complete the following information):**
 - Helm Version: 3.1.2
 - Kubernetes Version 1.18.0

**Additional context**
I can't find much information about Helm 3 support in this repository, but I can see that you test for helm 3 support. Am I missing something?

**Comment by lucasreed** [comment]
Thanks for bringing this to our attention. It certainly looks related to [this issue](https://github.com/helm/helm/issues/6864) in helm. Since our tests are installing with a local copy of the chart it makes sense that tests are passing. We will investigate what changes we can potentially make to ensure it works in both helm 2 and 3.

**Comment by bittermandel** [comment]
Sorry, this was just a misleading error message by Helm. I used the wrong order of chart name and release name! Took a while to figure out :smile: 

PS: We good. Issue can be closed!

**Comment by lucasreed** [comment]
Ah ok, good to know. Glad it's working and thanks for the update!
